"""Markdown tables generated from summary.csv, so documents can quote the artifact."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

STRATEGY_ORDER = ["naive", "confidence", "provenance", "verified", "quarantine"]


def _fmt(v) -> str:
    if isinstance(v, float):
        return "n/a" if pd.isna(v) else f"{v:.3f}"
    return str(v)


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(_fmt(row[c]) for c in cols) + " |")
    return "\n".join(lines)


def _pick(summary: pd.DataFrame, exp: str, cols: list[str], keep: list[str]) -> pd.DataFrame:
    d = summary[summary.experiment == exp]
    out = d[keep + [f"{c}_mean" for c in cols]].copy()
    out.columns = keep + cols
    return out


def build_report(summary: pd.DataFrame) -> str:
    n = int(summary.n_seeds.iloc[0])
    parts = [f"# Quick benchmark tables\n\nGenerated by `python -m provmem report` from `summary.csv` "
             f"(mean over {n} seeds). Sample standard deviations are in `summary.csv` "
             "(`*_sd` columns). They describe sensitivity to seeded simulator variation; "
             "they are not confidence intervals or independent real-system trials.\n"]

    s = _pick(summary, "strategies",
              ["asr_post_mean", "false_retrieval_rate", "answer_flip_rate", "propagation_final",
               "exposure_final", "clean_accuracy_mean", "fp_reject_rate", "fn_accept_injected",
               "recovery_rounds", "recovered", "context_tokens_per_query", "verifier_lookups",
               "messages"], ["scenario", "strategy"])
    s = s.rename(columns={"asr_post_mean": "asr", "false_retrieval_rate": "false_retr",
                          "answer_flip_rate": "flip", "propagation_final": "propag",
                          "exposure_final": "exposure", "clean_accuracy_mean": "clean_acc",
                          "fn_accept_injected": "fn_accept", "context_tokens_per_query": "tokens/q",
                          "verifier_lookups": "lookups"})
    parts.append("## strategies\n\n" + md_table(s))

    t = _pick(summary, "threshold", ["asr_post_mean", "false_retrieval_rate", "clean_accuracy_mean",
                                     "clean_unknown_final", "fp_reject_rate", "fn_accept_injected"],
              ["scenario", "strategy", "value"])
    parts.append("## threshold\n\n" + md_table(t))

    h = _pick(summary, "hops", ["asr_post_mean", "clean_accuracy_mean", "fp_reject_rate",
                                "fn_accept_injected", "propagation_final"],
              ["scenario", "strategy", "value"]).rename(columns={"value": "max_hops"})
    parts.append("## hops\n\n" + md_table(h))

    a = _pick(summary, "agents", ["asr_post_mean", "propagation_final", "clean_accuracy_mean",
                                  "verifier_lookups", "messages"], ["scenario", "strategy", "value"])
    parts.append("## agents\n\n" + md_table(a.rename(columns={"value": "n_agents"})))

    g = _pick(summary, "agreement", ["asr_post_mean"], ["strategy", "variant"])
    g = g.pivot(index="variant", columns="strategy", values="asr_post_mean")[
        ["naive", "provenance", "verified"]].reset_index()
    parts.append("## agreement (attack success rate, forged_meta)\n\n" + md_table(g))

    k = _pick(summary, "k", ["asr_post_mean", "false_retrieval_rate", "clean_accuracy_mean",
                             "context_tokens_per_query", "scored_per_query"],
              ["scenario", "strategy", "value"])
    parts.append("## k\n\n" + md_table(k.rename(columns={"value": "k"})))

    ab = _pick(summary, "ablation", ["asr_post_mean", "false_retrieval_rate", "clean_accuracy_mean",
                                     "fp_reject_rate", "fn_accept_injected"],
               ["scenario", "strategy", "variant"])
    parts.append("## ablation\n\n" + md_table(ab))

    c = _pick(summary, "coverage", ["asr_post_mean", "false_retrieval_rate", "clean_accuracy_mean",
                                    "fp_reject_rate", "fn_accept_injected", "verifier_lookups"],
              ["scenario", "strategy", "variant", "param", "value"])
    parts.append("## coverage and verifier noise\n\n" + md_table(c))
    return "\n\n".join(parts) + "\n"


def write_outputs(summary: pd.DataFrame, out: Path, plots: bool = True) -> list[Path]:
    written: list[Path] = []
    experiments = set(summary.experiment)
    if plots and {"strategies", "threshold"} <= experiments:
        from .plots import strategy_comparison, threshold_tradeoff
        strategy_comparison(summary, out / "strategy_comparison.png")
        threshold_tradeoff(summary, out / "threshold_tradeoff.png")
        written += [out / "strategy_comparison.png", out / "threshold_tradeoff.png"]
    if set(_EXPECTED) <= experiments:
        (out / "report.md").write_text(build_report(summary), encoding="utf-8", newline="\n")
        written.append(out / "report.md")
    return written


_EXPECTED = ("strategies", "threshold", "hops", "agents", "agreement", "k", "ablation", "coverage")
